language: c
compiler: clang
matrix:
  include:
    - os: linux
      arch: amd64
    - os: linux
      arch: arm64
    - os: osx
      arch: amd64

addons:
  apt:
    packages:
      - libreadline-dev

script:
  - make
  - mv dist/baik baik-$TRAVIS_OS_NAME-`uname -m`

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file: baik-$TRAVIS_OS_NAME-`uname -m`
  skip_cleanup: true
  on:
    tags: true